# Generated by Django 3.2.13 on 2023-09-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idade',
            field=models.CharField(default='dez', max_length=100),
        ),
    ]
