# Generated by Django 3.2.13 on 2023-09-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230922_0216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-update', '-created']},
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='base.Tag'),
        ),
    ]
