# Generated by Django 3.2.13 on 2023-10-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
