# Generated by Django 3.2.13 on 2023-10-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='melhor_resposta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='melhor_resposta',
            field=models.BooleanField(default=False),
        ),
    ]
