# Generated by Django 3.2.13 on 2023-10-11 11:46

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20231008_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
