# Generated by Django 3.2.13 on 2023-10-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_quillpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
    ]
