# Generated by Django 3.2.13 on 2023-11-02 13:45

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_quillpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
