# Generated by Django 3.2.13 on 2023-11-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='tags',
            field=models.ManyToManyField(null=True, to='base.Tag'),
        ),
    ]
