# Generated by Django 3.2.13 on 2023-11-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20231104_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='tags',
            field=models.ManyToManyField(null=True, to='base.Tag'),
        ),
    ]
