# Generated by Django 3.2.13 on 2023-11-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20231104_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
    ]
