# Generated by Django 3.2.13 on 2023-11-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_forumpost_anonimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
