# Generated by Django 3.2.13 on 2023-11-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_profile_unread_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_image',
            field=models.ImageField(default='logo.png', null=True, upload_to=''),
        ),
    ]
