# Generated by Django 3.2.13 on 2023-11-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_comentario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraProibida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
